#!/bin/bash

if [[ ${#@} -ne 0 ]] && [[ "${@#"--help"}" = "" ]]; then
  printf -- "\nThis script gives deeper insight into a directory.;
  exit 0;
fi;

echo 'Folder-rundown'

sleep 1

num_of_files=$(ls | wc -l)
echo 'There are' $num_of_files 'items total in this directory'
count=1



num_of_dir=$(find . -type d | wc -l)
counter=`expr $num_of_dir - 1`

echo "There are" $counter "directories inside this folder"

echo "---------------------------------------------------"

echo "The biggest file is size" 
ls -al ./ | cut -d " " -f 5- | awk -F ' ' '{print $(1)}' > temp_big_file.txt




cat temp_big_file.txt | sort -nr | head -1
echo "---------------------------------------------------"

rm temp_big_file.txt 




#most recent date modified


test="$(ls -lt ./ | head -n 2 | tail -n 1 | awk -F ' ' '{print $(NF)}')"
echo "The most recently modified file is:" $test 
test2=$(ls -lt ./ | head -n 2 | tail -n 1 | awk -F ' ' '{print $(NF-1), $(NF-3), $(NF-2)}')


echo "This modification occured at approximately" $test2
#ls -al ./ | awk -F ' ' '{print $(7)}' > dates2temp.txt ;\
#ls -al ./ | awk -F ' ' '{print $(6)}' > dates3temp.txt

#cat datestemp.txt | tail -n +2 > dates1temp.txt
#cat dates1temp.txt

#cat dates1temp.txt | nl > dates1_lined.txt
#cat dates2temp.txt | nl > dates2_lined.txt
#cat dates3temp.txt | nl > dates3_lined.txt

#awk  dates1_lined.txt > dates1_lined_v1.txt
#awk  dates2_lined.txt > dates2_lined_v1.txt
#awk  dates3_lined.txt > dates3_lined_v1.txt




#join dates1_lined_v1.txt dates3_lined_v1.txt > 1_3combo.txt
#join 1_3combo.txt dates2_lined_v1.txt > full_combo.txt
#cat full_combo.txt | cut -f2- -d  > combo_no_ln.txt





#while [ $count < num_of_files ]
#do 
 
